"""OPUS-FILLS (Phase 4). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 4 — implement against the module docstring contract")

def test_inv_demote_not_delete(tiny_instance): ...
def test_ratio_demotion_before_cap_enforcement(tiny_instance): ...
def test_dormant_rules_edges_excluded_from_resolve(tiny_instance): ...
