"""OPUS-FILLS (Phase 4). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 4 — implement against the module docstring contract")

def test_parses_fixture_log_6_entries(tiny_instance): ...
def test_parses_live_log_11_entries(): ...
def test_append_refuses_duplicate_id(tiny_instance): ...
def test_advance_status_legal_transitions_only(tiny_instance): ...
