"""OPUS-FILLS (Phase 3). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 3 — implement against the module docstring contract")

def test_inv_path_product_exact(tiny_instance): ...
def test_weighted_prefers_higher_confidence_route(tiny_instance): ...
def test_below_floor_is_weak_answer(tiny_instance): ...
