"""OPUS-FILLS (Phase 4). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 4 — implement against the module docstring contract")

def test_inv_freeze_idempotent(tiny_instance): ...
def test_freeze_requires_approve_on_non_self_approve(): ...
def test_freeze_writes_fact_loop_rows_and_counters(tiny_instance): ...
