"""OPUS-FILLS (Phase 3). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 3 — implement against the module docstring contract")

def test_inv_no_support_refuses_with_stub(tiny_instance): ...
def test_inv_cycle_classes(tiny_instance): ...
def test_missing_confidence_refuses(tiny_instance_bare): ...
