"""OPUS-FILLS (Phase 1). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 1 — implement against the module docstring contract")

def test_inv_null_confidence_refuses(tiny_instance_bare): ...
def test_inv_unknown_kind_raises(tiny_instance): ...
def test_reads_are_profile_driven(tiny_instance): ...
