"""OPUS-FILLS (Phase 2). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 2 — implement against the module docstring contract")

def test_m001_backfills_bare_tiny(tiny_instance_bare): ...
def test_m001_idempotent_second_run_zero(tiny_instance_bare): ...
def test_m001_dry_run_writes_nothing(tiny_instance_bare): ...
