"""OPUS-FILLS (Phase 4). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 4 — implement against the module docstring contract")

def test_stage_writes_matcher_v2_with_machine_block(tiny_instance): ...
def test_verify_requires_provenance_fired(tiny_instance): ...
def test_verify_rejects_on_failed_confirm(tiny_instance): ...
