"""OPUS-FILLS (Phase 5/6). Named tests are the contract — see tests/INVARIANTS.md."""
import pytest

pytestmark = pytest.mark.skip(reason="OPUS-FILLS: Phase 5/6 — implement against the module docstring contract")

def test_frontier_rate_matches_independent_parse(): ...
def test_ab_tasks_frozen_hash_and_subsets(): ...
def test_ab_variants_share_recomputed_answer_keys(): ...
def test_ab_report_splits_corpus_private(): ...
